### ISSUE TITLE
No such file or directory: 'data/KITTI/samples.pkl'

### ISSUE THREAD

**Issue by HaiCLi** [norlab-ulaval/mask_bev#1]
Hi, 

I used the following commands to download the dataset and make the folder tree like this. However,  I didn't find the 'data/KITTI/samples.pkl'. Is there anything I missed?

commands for downloading: "# Velodyne data
wget https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_velodyne.zip
# Calib mats
wget https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_calib.zip
# Training labels
wget https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_label_2.zip
# Dev kit for reference
wget https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_object.zip
# Sequence data
wget https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_road_mapping.zip

# Download splits
wget -c  https://raw.githubusercontent.com/traveller59/second.pytorch/master/second/data/ImageSets/test.txt
wget -c  https://raw.githubusercontent.com/traveller59/second.pytorch/master/second/data/ImageSets/train.txt
wget -c  https://raw.githubusercontent.com/traveller59/second.pytorch/master/second/data/ImageSets/val.txt
wget -c  https://raw.githubusercontent.com/traveller59/second.pytorch/master/second/data/ImageSets/trainval.txt

# then unzip everything"

Folder tree:
![image](https://github.com/user-attachments/assets/9a06f124-1279-4728-b3e3-b43697107fb5)

Thanks for your help in advance!

**Comment by willGuimont** [comment]
Hi,

Thanks for raising this issue! I’ve updated the documentation in `docs/TRAINING.md` to clarify how to generate `data/KITTI/samples.pkl`.

To generate the file, you can run the following command:

```shell
PYTHONPATH=. python scripts/generate_kitti_object_sampler.py
```

Let me know if you have any other questions!

**Comment by HaiCLi** [comment]
> Hi,
> 
> Thanks for raising this issue! I’ve updated the documentation in `docs/TRAINING.md` to clarify how to generate `data/KITTI/samples.pkl`.
> 
> To generate the file, you can run the following command:
> 
> ```shell
> PYTHONPATH=. python scripts/generate_kitti_object_sampler.py
> ```
> 
> Let me know if you have any other questions!

I think this command can not solve this problem. It seems that running this command requires "data/KITTI/samples.pkl", rather than outputting the file.  "data/KITTI/samples.pkl" is the prerequirement.

![image](https://github.com/user-attachments/assets/b3e38b6a-52fc-4753-a46b-bf482fa39210)

**Comment by willGuimont** [comment]
Hi,

I think the issue stems from the fact that `data/KITTI/` does not exist, hence the `No such file or directory` error.

Are you running the code in Docker? Did you add the volume containing the data to the correct location? It can be added using the `-v ./data/KITTI:data/KITTI` flag in Docker.

From the root of the project, you should be able to list the content of `KITTI`:
```shell
ls data/KITTI
```

Otherwise, I would suggest following the updated instructions in `docs/TRAINING.md`, with the most up-to-date version of the code:

```
docker build -t mask_bev .
export CUDA_VISIBLE_DEVICES=0

docker run --gpus all -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES --rm -it \
  -v .:/app \
  -v ./data/KITTI:/app/data/KITTI \
  -v /dev/shm:/dev/shm \
  mask_bev bash -c "PYTHONPATH=. python3.10 scripts/generate_kitti_object_sampler.py"
```

Let me know if it works!

**Comment by HaiCLi** [comment]
> Hi,
> 
> I think the issue stems from the fact that `data/KITTI/` does not exist, hence the `No such file or directory` error.
> 
> Are you running the code in Docker? Did you add the volume containing the data to the correct location? It can be added using the `-v ./data/KITTI:data/KITTI` flag in Docker.
> 
> From the root of the project, you should be able to list the content of `KITTI`:
> 
> ```shell
> ls data/KITTI
> ```
> 
> Otherwise, I would suggest following the updated instructions in `docs/TRAINING.md`, with the most up-to-date version of the code:
> 
> ```
> docker build -t mask_bev .
> export CUDA_VISIBLE_DEVICES=0
> 
> docker run --gpus all -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES --rm -it \
>   -v .:/app \
>   -v ./data/KITTI:/app/data/KITTI \
>   -v /dev/shm:/dev/shm \
>   mask_bev bash -c "PYTHONPATH=. python3.10 scripts/generate_kitti_object_sampler.py"
> ```
> 
> Let me know if it works!

I solved this by reinstall the requirement.txt. But didn't know why, whatever it was solved.
